version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      maven-minor-patch:
        update-types:
          - "minor"
          - "patch"
      maven-major:
        update-types:
          - "major"
    labels:
      - "dependencies"
      - "maven"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
      npm-major:
        update-types:
          - "major"
    labels:
      - "dependencies"
      - "npm"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        update-types:
          - "minor"
          - "patch"
      actions-major:
        update-types:
          - "major"
    labels:
      - "dependencies"
      - "github-actions"
